#Database details
database:
  # A Data Source Name (dsn) is a connection string of the form:
  # driver://username:password@hostname/databasename
  dsn: mysql://silkuser:usersilk@localhost/silkframework_com
  prefix: silk_

#Should we be in debug mode?
debug: false

#Places to look for classes when autoloading
class_autoload:
  - app/models
